---
version: "2.11"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - /media/pi/Sensehack_Media/Movies:/movies
      - /media/pi/Sensehack_Media/Bluray:/bluray
      - /media/pi/Sensehack_Media/Downloads:/downloads
      - /media/pi/Sensehack_Media/Downloads/completed:/downloads_complete
      - /media/pi/Sensehack_Media/Downloads/downloading:/downloading
    ports:
      - 7878:7878
    restart: unless-stopped
