---
version: "2.11"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr_manual
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr_manual/data:/config
      - /media/pi/SensehackMedia/TV:/tv
      - /media/pi/SensehackMedia/TV 1:/tv_1
      - /media/pi/SensehackMedia/TV 2:/tv_2
      - /media/pi/SensehackMedia/TV 3:/tv_3
      - /media/pi/SensehackMedia/TV 4:/tv_4
      - /media/pi/SensehackMedia/TV 5:/tv_5
      - /media/pi/SensehackMedia/Cartoon:/cartoon
      - /media/pi/SensehackMedia/Cartoon 1:/cartoon_1
      - /media/pi/SensehackMedia/Cartoon 2:/cartoon_2
      - /media/pi/SensehackMedia/Cartoon 3:/cartoon_3
      - /media/pi/SensehackMedia/Cartoon 4:/cartoon_4
      - /media/pi/SensehackMedia/Cartoon 5:/cartoon_5
      - /media/pi/SensehackMedia/Downloads:/downloads
      - /media/pi/SensehackMedia/Downloads/completed:/downloads_complete
      - /media/pi/SensehackMedia/Downloads/downloading:/downloading
    ports:
      - 8989:8989
    restart: unless-stopped
