---
version: "2.11"
services:
  sonarr:
    image: ahuh/arm-jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
      - AUTO_UPDATE=true `#optional`
      - RUN_OPTS= `#optional`
    volumes:
      - /path/to/data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped



# docker run -d \
#   --name=jackett \
#   -e PUID=1000 \
#   -e PGID=1000 \
#   -e TZ=Etc/UTC \
#   -e AUTO_UPDATE=true `#optional` \
#   -e RUN_OPTS= `#optional` \
#   -p 9117:9117 \
#   -v /path/to/data:/config \
#   -v /path/to/blackhole:/downloads \
#   --restart unless-stopped \
#   ahuh/arm-jackett