---
version: "2.11"
services:
  jackett:
    # This has problems starting up on Raspberry Pi v4 (64bit ARMv8) but docker / portainer space is 32Bit is my understanding.
    # image: linuxserver/jackett:arm64v8-latest
    # This below has `curl -vvv https://1337x.to/` SSL 443 connection refuse error for trackers
    # image: ahuh/arm-jackett 
    # This works fine with index / trackers
    image: linuxserver/jackett:arm32v7-version-v0.20.754
    container_name: jackett_new
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

# Actual Docker command
# https://hub.docker.com/r/linuxserver/jackett

# docker run -d \
#   --name=jackett \
#   -e PUID=1000 \
#   -e PGID=1000 \
#   -e TZ=Etc/UTC \
#   -e AUTO_UPDATE=true `#optional` \
#   -e RUN_OPTS= `#optional` \
#   -p 9117:9117 \
#   -v /path/to/data:/config \
#   -v /path/to/blackhole:/downloads \
#   --restart unless-stopped \
#   ahuh/arm-jackett