version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            - OPENVPN_PROVIDER=VPNUNLIMITED
            #- OPENVPN_CONFIG=ca-tr
            - OPENVPN_CONFIG=fr
            - OPENVPN_USERNAME=safa@gmail.com
            - OPENVPN_PASSWORD=sagfawr

            # This below line solves the infamous OpenSSL: Cannot Load inline Certificate file https://github.com/haugene/vpn-configs-contrib/issues/162
            - OPENVPN_OPTS=--tls-cipher DEFAULT:@SECLEVEL=0
            
            ## New Custom config
            # - OPENVPN_PROVIDER=custom
            # - OPENVPN_CONFIG=fr
            # - OPENVPN_USERNAME=user
            # - OPENVPN_PASSWORD=pass
            # Very important to mention this local network mask or else you won't be able to access your containers or services.
            - LOCAL_NETWORK=10.0.0.0/24
            
            ## Transmission Config
            - TRANSMISSION_WEB_UI=transmission-web-control
            - TRANSMISSION_DOWNLOAD_DIR=/downloading
            - TRANSMISSION_INCOMPLETE_DIR=/incomplete
            - TRANSMISSION_WATCH_DIR=/downloads_watch
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'

        volumes:
            - /etc/openvpn/custom_2023:/etc/openvpn/custom/
            - /media/pi/SensehackMedia/Downloads:/downloads
            - /media/pi/SensehackMedia/Downloads/downloading:/downloading
            - /media/pi/SensehackMedia/Downloads/incomplete:/incomplete
            - /media/pi/SensehackMedia/Downloads/completed:/downloads_complete
            - /media/pi/SensehackMedia/Downloads/watch:/downloads_watch    
        # Please comment this next line when restarting raspberry pi server since it creates folder references before the external HDD mounts
        restart: unless-stopped

        image: haugene/transmission-openvpn
        container_name: transmission-vpn