version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /media/pi/SensehackMedia/Downloads:/downloads
            - /media/pi/SensehackMedia/Downloads/downloading:/downloading
            - /media/pi/SensehackMedia/Downloads/incomplete:/incomplete
            - /media/pi/SensehackMedia/Downloads/completed:/downloads_complete
            - /media/pi/SensehackMedia/Downloads/watch:/downloads_watch
            
        environment:
            - OPENVPN_PROVIDER=VPNUNLIMITED
            - OPENVPN_CONFIG=ca-tr
            - OPENVPN_USERNAME=safa@gmail.com
            - OPENVPN_PASSWORD=sagfawr
            - LOCAL_NETWORK=192.168.0.0/24
            - TRANSMISSION_WEB_UI=transmission-web-control
            - TRANSMISSION_DOWNLOAD_DIR=/downloading
            - TRANSMISSION_INCOMPLETE_DIR=/incomplete
            - TRANSMISSION_WATCH_DIR=/downloads_watch
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'

        image: haugene/transmission-openvpn
        container_name: transmission-vpn
